//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon17
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServices
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public int ServiceId { get; set; }
    
        public virtual Services Services { get; set; }
        public virtual Users Users { get; set; }
    }
}
